name: Test Suites

# We are a reusable Workflow only
on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: false

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    env:
      DB_USER: root
      DB_PASSWORD: root
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        jdkVersion: ["21"]
        experimental: [false]
        #include:
        #- jdkVersion: "17"
        #  os: "windows-latest"
        #  experimental: true
        # Disabled for now until we can figure out the gradle matrix
        #- jdkVersion: "17"
        #  os: "ubuntu-latest"
        #  experimental: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.jdkVersion }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: "8.7"

      - name: Test Module
        run: |
          ./gradlew downloadBoxLang
          # this is done in order to build the module structure before testing
          ./gradlew shadowJar test --stacktrace --console=plain

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests-${{ matrix.os }}-${{ matrix.jdkVersion }}
          path: |
            **/build/reports/tests/**
            **/build/test-results/**

  publish-test-results:
    name: Publish Test Results
    runs-on: ubuntu-latest
    needs: tests
    if: always()
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            artifacts/**/*.xml
